(function() {  
    return {
	certfilemng: "인증서 파일 관리",
	certinfomng: "인증서 정보 관리",
	changecancel: "인증서 암호 변경이 취소되었습니다.",
	changeok: "인증서 암호가 변경되었습니다.",
	changefail: "인증서 암호 변경에 실패하였습니다.",
	changepass: "인증서 암호 변경",
	copy: "인증서 복사",
	copycancel: "인증서 복사가 취소되었습니다.",
	copyconfirm: "같은 이름의 인증서가 이미 존재합니다.\n기존의 인증서를 삭제하고 새로운 인증서를 저장하시겠습니까?",
	copyfail: "인증서 복사에 실패했습니다.\n같은 인증서가 존재하거나 저장할 수 없는 매체입니다.",
	copyfail_iccard: "인증서 복사에 실패했습니다.\n같은 인증서가 존재하거나 2048 인증서는 저장할 수 없는 매체입니다.",
	copyfail_ubikey: "인증서 복사가 취소되었거나 오류가 발생했습니다.",
	copyingcert: "... [인증서 복사중] 잠시 기다려 주십시오 ...",
	copyok1: "선택한 인증서를 [",
	copyok2: "]에서 [",
	copyok3: "]으로 복사하였습니다.",
	copysamemedia: "복사할 원본 매체와 대상 매체가 동일합니다.",
	deletecert: "인증서 삭제",
	deletecancel: "인증서 삭제가 취소되었습니다.",
	deleteconfirm: "인증서[%cert,] 삭제를 선택하셨습니다.\n정말로 삭제하시겠습니까?",
	deleteconfirm2: "선택된 인증서는 영구히 삭제됩니다.\n계속하시겠습니까?",
	deletefail: "인증서 삭제에 실패하였습니다.",
	deleteok: "인증서를 삭제하였습니다.",
	descdelete: "선택한 인증서를 삭제합니다.",
	descinstall: "신뢰하지 않는 경우 인증서를 재설치합니다.",
	descroot: "최상위 인증기관의 신뢰여부를 확인합니다.",
	descvertify: "선택한 인증서의 상세정보를 봅니다.",
	gettingcert: "... [인증서 가져오는 중] 잠시 기다려 주십시오 ...",
	hdd: "하드디스크",
	hddlist: "하드디스크의 인증서 목록입니다.",
	iccard: "IC 카드",
	iccardlist: "스마트카드의 인증서 목록입니다.",
	kepcoiccard: "KEPCO IC 카드",
	importexport: "내보내기/가져오기",
	exportcert: "인증서 내보내기",
	importcert: "인증서 가져오기",
	installroot: "인증서 설치",
	mounterror: "존재하지 않는 인증서 관리창입니다.",
	nocert: "해당 인증서가 존재하지 않습니다.",
	noremovable: "시스템에 이동식 드라이브가 없거나 이동식 드라이브에 저장된 인증서가 없습니다.",
	noselection: "인증서를 선택하지 않았습니다.",
    noselection_media: "저장매체를 선택하지 않았습니다.",
	notfoundusb: "시스템의 이동식 드라이브를 찾을 수 없습니다.",
	notsupportexport: "[내보내기]가 지원되지 않는 저장매체입니다.",
	notsupportimport: "[가져오기]가 지원되지 않는 저장매체입니다.",
    notsupportexportimport: "[내보내기/가져오기]가 지원되지 않는 저장매체입니다.",
	ownerverify: "인증서 소유자 검증",
	phonelist: "휴대폰내의 인증서 목록입니다.",
	pkcs11: "보안토큰",
	pkcs11cancel: "보안토큰 비밀번호 입력이 취소되었습니다.",
	pkcs11incorrect: "잘못된 보안토큰 비밀번호입니다.",
	pkcs11list: "보안토큰(PKCS#11)의 인증서 목록입니다.",
	pkcs11selectcancel: "보안토큰 선택이 취소되었습니다.",
	pricatab: "사설 인증기관",
	privatecert: "일반인증서",
	pubcatab: "공인 인증기관",
	removable: "이동식디스크",
	removablelist: "이동식디스크의 인증서 목록입니다.",
	rootcert: "최상위인증기관",
	roottab: "최상위 공인 인증기관",
	rootverify: "루트인증기관 검증",
	title: "인증서 관리",
	usertab: "개인",
	verifycancel: "주민등록(사업자등록)번호 검증이 취소되었습니다.",
	verifyidnerr: "입력된 주민등록(사업자등록)번호가 일치하지 않습니다.\n주민등록(사업자등록)번호를 다시 한 번 확인하십시오.",
	verifyingcert: "인증서를 검증하는 중입니다...",
	verifypasserr: "인증서 암호가 올바르지 않습니다.\r\n인증서 암호는 대문자 소문자를 구분합니다.\r\n<Caps Lock>키가 켜져 있는지 확인하시고 다시 입력하십시오.",
	verifyvid: "입력된 주민등록(사업자등록)번호가 인증서의 \n주민등록(사업자등록)번호와 일치합니다.",
	verifyvidtitle: "주민등록(사업자등록)번호 검증",
	verify: "인증서 보기/검증",
	warningcsp: "아직지원되지 않는 기능입니다.",
	warningfloppy: "아직지원되지 않는 기능입니다.",
	warningiccard: "아직지원되지 않는 기능입니다.",
	importsuccess: "인증서 가져오기 성공",
	importfail: "인증서 가져오기 실패",
	importcancel: "인증서 가져오기 취소",
	exportcomplete: "인증서 내보내기 완료",
	exportsuccess: "인증서 내보내기 성공",
	exportfail: "인증서 내보내기 실패",
	exportcancel: "인증서 내보내기 취소",
	incorrect_kmcertPW: "암호화용 인증서의 비밀번호가 다릅니다.\n복구하시려면 재발급이 필요합니다.\n자세한 사항은 관리자에게 문의 하십시오",
	
	media_location: "인증서 위치",
	media_localstorage: "브라우저",
	media_memorystorage: "인증서찾기",
	media_hdd: "하드디스크",
	media_iccard: "IC카드",
	media_mobile: "휴대폰",
	media_pkcs11: "보안토큰",
	media_removable: "이동식디스크",
	media_savetoken: "저장토큰",
	media_securedisk: "안전디스크",
    media_xfs: "프리싸인",
	media_left:"◀",
	media_right:"▶",
	media_left_title:"이전",
	media_right_title:"다음",

	mobile_mobi: "휴대폰 인증서 저장/전자서명(금융결제원)",
	mobile_info: "휴대폰 인증서 저장 서비스",

	table_expire: "만료일",
	table_issuer: "발급자",
	table_section: "구분",
	table_user: "사용자",

	button_ok: "확인",
	button_cancel: "취소",
	
	open_new_window: "새창 열림 ",
	open_layer: "레이어 열림 ",
	xvvcursor_guide: "인증서 관리 레이어가 열렸습니다. 센스리더 사용자는 원활한 사용을 위해 가상커서를 해제해주시기 바랍니다. 가상커서는 현재 위치에서 엔터키를 입력하면 해제됩니다.",

	installNotify: "휴대폰 인증 설치 페이지로 이동하시겠습니까?",
	installNotifyHSM: "현재 사용가능한 상태가 아닙니다.\n\n보안토큰 구동프로그램을 설치하시겠습니까?",
	pkcs11List: "보안토큰(PKCS#11)의 인증서 목록입니다.",
	tokenNotify: "보안 토큰(USB/IC카드 등)이 정상적으로 꽂혀 있는지 확인하십시오.",

	/* 접근성 */
	banner: "배너",
	certtable: "인증서 목록",
	table_summary: "구분, 사용자, 만료일, 발급자",
	
	table_select: "선택 ",
	cert_status0: "정상 인증서",
	cert_status1: "만료 예정 인증서",
	cert_status2: "만료 된 인증서",

	media_removable_list: "이동식디스크 목록 상자",
	media_savetoken_list: "저장토큰 목록 상자",
	
	close: "닫기",

	blank: "",

	notSupported: "지원하지 않는 기능입니다.",
	
	/* 20130219 synchronized as-is */
	savetoken_msg: "해당 보안토큰 구동프로그램 정보를 찾을 수 없습니다.\n(http://www.rootca.or.kr에서 관련 내용을 확인하시기 바랍니다.)",
	rootca_url: "http://www.rootca.or.kr",

	anysign4pc_update: "[AnySign for PC] 공인인증 보안 프로그램 설치가 필요합니다.\n[확인]을 선택하시면 설치페이지로 연결됩니다.",
	selectKeyworderror: "인증서 암호가 올바르지 않습니다.\n인증서 암호는 대문자 소문자를 구분합니다.\n<Caps Lock>키가 켜져 있는지 확인하시고 다시 입력하십시오.",
	notsupportexport_flash: "인증서 내보내기 기능을 사용할 수 없습니다.\n웹브라우저(Internet Explorer)에 저장된 인증서를 파일로 내보내기 위해선 플래시 10 이상이 설치되어 있어야 합니다.\nAdobe 홈페이지에 접속하여 플래시 설치 후 이용하시기 바랍니다.",
	
	securedisk_install: "안전디스크 프로그램이 설치되어 있지 않습니다.\n설치페이지로 이동하시겠습니까?",
	securedisk_notable: "안전디스크 프로그램이 설치되어 있지 않거나 사용할 수 없습니다.",
	securedisk_error: "안전디스크 실행 중 오류가 발생하였습니다.",
	
	kepcoiccard_notable: "KEPCO IC Card 프로그램이 설치되어 있지 않거나 사용할 수 없습니다.",
    
    xfs_no_cert: "사용 가능한 인증서가 없습니다."
	}
})();
